Resolved Implement OAM Services for version 2.0.0
openBackhaul/OamLog pull request #174
Opened 2023-02-08 08:27 UTC by ManasaBM1

Fixes #155

2023-02-08 08:53 UTC, ManasaBM1 commented
Reviewer is @DanaSunal

2023-02-09 09:50 UTC, DanaSunal requested changes

2023-02-09 09:50 UTC, DanaSunal commented on server/controllers/ActionProfile.js
> +var utils = require('../utils/writer.js');
not used

2023-02-09 10:13 UTC, ManasaBM1 commented on server/service/TcpServerService.js
> +  "tcp-server-interface-1-0:description" : "tcp-server-interface-1-0:"+value
removed the "tcp-server-interface-1-0:

2023-02-09 10:14 UTC, ManasaBM1 commented on server/service/TcpServerService.js
> +  }
done

2023-02-09 10:16 UTC, ManasaBM1 commented on server/controllers/ActionProfile.js
> +var utils = require('../utils/writer.js');
removed done

2023-02-10 14:49 UTC, DanaSunal approved these changes

2023-02-10 14:50 UTC, merged