Update UUIDs of Services
openBackhaul/OamLog pull request #73
Opened 2022-11-15 13:19 UTC by openBackhaul

**Process for updating the UUIDs of Services**
- [x] Thorsten to check categories of OperationServers and OperationClients in ServiceList
- [ ] Iswaryaa to review categories of OperationServers and OperationClients in ServiceList
- [ ] Katharina to add new UUIDs based on category of operation (but not old UUID) in ServiceList
- [ ] Iswaryaa to review new UUIDs in ServiceList
- [ ] Katharina to CTRL+h for old UUIDs and replace them by new UUIDs in ForwardingList, CONFIGfile and OAS.
- [ ] Katharina to step through ForwardingList, CONFIGfile and OAS and compare every UUID against new one in ServiceList
- [ ] Iswaryaa to review new UUIDs in ForwardingList, CONFIGfile and OAS
If no errors found
- [ ] Iswaryaa to delete old UUIDs in ServiceList
- [ ] Iswaryaa to merge the feature branch into develop
- [ ] Iswaryaa to close this issue and delete the feature branch on GitHub

2022-11-16 05:34 UTC, IswaryaaS commented
OamLog+services.yaml file looks fine for categories of services

2022-11-17 05:29 UTC, IswaryaaS requested changes
@kmohr-soprasteria , requesting change for a single comment

2022-11-17 05:29 UTC, IswaryaaS commented on OamLog+services.yaml
> +                  ol-1-0-0-op-c-im-ne-1-0-0-000
A small typo mistake here in uuid ol-1-0-0-op-c-im-ne-1-0-0-000 . application-id to be replaced with nr instead of ne

2022-11-17 08:35 UTC, IswaryaaS approved these changes
Changes in service.yaml file looks fine. We can now proceed for updating other files.

2022-11-21 06:56 UTC, IswaryaaS requested changes

2022-11-21 12:00 UTC, kmohr-soprasteria commented
- Talked to Thorsten about the fc uuids - those shall not be changed with this pull request.
- Merged changes from develop branch
- @IswaryaaS: you can continue with your part

2022-11-21 12:57 UTC, IswaryaaS approved these changes

2022-11-21 12:57 UTC, merged